version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "boilerplateapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wtkywtzkypal"
s3_prefix = "boilerplateapp"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

